version: '3.3'
services:
  # db:
  #   image: postgres:15.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=comic_user
  #     - POSTGRES_PASSWORD=password
  #   ports:
  #     - '5432:5432'

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app

  app:
    image: comic
    command: gunicorn ComicDemo2.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - ./.env   
